import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NavBar from "@/components/NavBar";
import icon from '@/public/icons/favicon.ico'
import "./globals.css";

const poppins = Poppins({
  display: "swap",
  weight: ['400', '600', '900'],
  subsets: ['latin']
})


export const metadata: Metadata = {
  title: "Teste Prático",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link
          rel="icon"
          href={icon.src}
        />
      </head>
      <body
        className={`${poppins.className} text-[18px] antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
